name: CI prueba

on:
  push:
    branches: [ master ]
  
jobs:
  build:

    runs-on: [ self-hosted, linux ]

    steps:
    - uses: actions/checkout@v2
    - run: npm install
    
  deploy:
    needs: [build]
    runs-on: [ self-hosted, linux ]
    steps:
    - run: pm2 reload app