name: CI prueba

on:
  push:
    branches: [ master ]
  
jobs:
  build:

    runs-on: [ self-hosted, linux ]

    steps:
    - run: pwd
    - run: cd ../../../../../github-actions-test
    - run: git pull
    - run: npm install
    
  deploy:
    needs: [build]
    runs-on: [ self-hosted, linux ]
    steps:
    - run: pm2 reload app